FROM centos:CENTOS_VERSION

ARG BUILD_DATE
ARG VCS_REF
ARG VERSION=CENTOS_VERSION

LABEL \
    org.label-schema.name="jumanjiman/infiniband" \
    org.label-schema.description="Infiniband base image based on Centos" \
    org.label-schema.url="https://github.com/jumanjihouse/docker-infiniband" \
    org.label-schema.vcs-url="https://github.com/jumanjihouse/docker-infiniband.git" \
    org.label-schema.docker.dockerfile="/Dockerfile.in" \
    org.label-schema.vcs-type="Git" \
    org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.version=$VERSION

RUN yum -y install CENTOS_RPMS && \
    yum -y update && \
    yum clean all

# http://www.mellanox.com/page/mlxup_firmware_tool
#
# mlxup - a Mellanox firmware update and query utility.
# The utility enables scanning the server machine for
# available Mellanox adapters and indicates
# whether firmware update is required for each adapter.
# To make it easier for customers the mlxup can also
# automatically update the latest firmware either from the web,
# or use binaries provided locally.
#
ADD http://www.mellanox.com/downloads/firmware/mlxup/4.5.0/linux_x64/mlxup /usr/sbin/mlxup
RUN chmod 0755 /usr/sbin/mlxup
