#!/bin/bash
set -e

. test/vars.bash

for version in ${CENTOS_VERSIONS}; do
  tag="${IMAGE}:${version}"
  echo
  echo '=====>' ${tag} >&2
  build_args="
    --build-arg BUILD_DATE=$(date +%Y%m%dT%H%M)
    --build-arg VCS_REF=${CIRCLE_SHA1:0:7}
  "
  sed -e "s/CENTOS_VERSION/${version}/g" -e "s/CENTOS_RPMS/${CENTOS_RPMS}/g" Dockerfile.in | docker build ${build_args} --rm -t ${tag} -
done

echo
echo '=====> Images' >&2
docker images | grep infiniband
