#!/bin/bash
set -e

cat > ci/vars <<EOF
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git rev-parse --short HEAD)
export TAG_BASE=\${BUILD_DATE}-git-\${VCS_REF}
EOF
. ci/vars

. test/vars.bash

for version in ${CENTOS_VERSIONS}; do
  tag="${IMAGE}:${version}"
  echo
  echo '=====>' ${tag} >&2
  build_args="
    --build-arg BUILD_DATE=${BUILD_DATE}
    --build-arg VCS_REF=${VCS_REF}
  "
  sed -e "s/CENTOS_VERSION/${version}/g" -e "s/CENTOS_RPMS/${CENTOS_RPMS}/g" Dockerfile.in | docker build ${build_args} --rm -t ${tag} -
done

echo
echo '=====> Images' >&2
docker images | grep infiniband
