#!/bin/sh
set -e

docker login -e ${mail} -u ${user} -p ${pass}
docker tag jumanjiman/infiniband:6 jumanjiman/infiniband:6-${1}
docker tag jumanjiman/infiniband:7 jumanjiman/infiniband:7-${1}
docker push jumanjiman/infiniband:6-${1}
docker push jumanjiman/infiniband:7-${1}
docker push jumanjiman/infiniband:6
docker push jumanjiman/infiniband:7
docker tag jumanjiman/infiniband:7 jumanjiman/infiniband:latest
docker push jumanjiman/infiniband:latest
docker logout
